### PR TITLE
Update zhs translation

### PR DESCRIPTION
**Pull request by yanang007**
ZHS translation for upcoming cards, keywords, powers, relics and UI contents.

And an overall check is made to keep everything up to date.

### CODE REVIEW

**Review by acourrau — APPROVED** [review]

**Comment by acourrau** [comment]
Thank you for grabbing all those changes!

**Comment by acourrau** [comment]
Would you be able to add ZHS for the `JorbsMod-Cull-Voiceover-Strings.json` file?

**Comment by yanang007** [comment]
@acourrau 

Yes, but it seems that the translation has already been update in #499 . I'm wondering is there any update that I missed?
Thank you for the heads-up.

**Comment by acourrau** [comment]
Forgive me, they are there I missed that. We did add 2 new things, shadow relic and repressed memory card (including a new power for the card). Would you look at those?

**Comment by yanang007** [comment]
Not a problem at all!
I have included translation for some of upcoming changes in the earlier update while they were still in PR at that point. However, I'm not at home right now, so it may take minutes to keep up with new changes.

**Comment by acourrau** [comment]
You're a machine, thank you!

**Pull request merged**
