### PR TITLE
Bugfix for Taunt Upgrade

### PR DESCRIPTION
**Pull request by acourrau**
Simple bugfix for taunt upgrade

### CODE REVIEW

**Comment by acourrau** [comment]
@yanang007 can you confirm I did the ZHS correctly? I just copied what it appeared to do for other cards.

**Comment by yanang007** [comment]
> @yanang007 can you confirm I did the ZHS correctly? I just copied what it appeared to do for other cards.

It is exactly what it's supposed to be! Thanks!

**Review by wang429 — APPROVED** [review]
Looks good to me, perhaps also mention the change in the changelog.

**Comment by acourrau** [comment]
> Looks good to me, perhaps also mention the change in the changelog.

Will add and merge!

**Pull request merged**
