### PR TITLE
Update zhs translation: new cards and wording changes

### PR DESCRIPTION
**Pull request by yanang007**
Translation for new cards:
 CoupDeGrace, FocusedRage,

Translation for new powers:
 CoupDeGracePower, OldBookPower, PossessionPower

### CODE REVIEW

**Comment by acourrau** [comment]
Just a heads up, I made some slight changes to the highlighting and wording of old book. I imagine the translations will need a cursory look. I'll hold off making any formal requests for updates until coup de grace gets merged, as changes are a possibility.

Thanks for the work! Very much appreciated!

**Comment by yanang007** [comment]
Got it! I will keep track on those new changes!
But I accidentally broke my repo... So I made another fork which left this PR invalid now. I probably need to close it and open another one when appropriate. Sorry for that...

**Comment by acourrau** [comment]
Not a problem at all! We're close on the merge for Coup De Grace I think, so it shouldn't be too long. We did add some new keywords for Coup De Grace, and it also affects an old card (True Strike).

**Comment by acourrau** [comment]
@yanang007 we're looking really good as far as progress goes. I think it's probably safe to update these translations.

**Pull request closed without merging**
