### PR TITLE
ZHS translation update: new cull cards and other changes

### PR DESCRIPTION
**Pull request by yanang007**
ZHS translation update

- New cards: Accumulation, Anxiety, Cleanse, Concentrate, Discordance, Exhale, Equinox, Feint, FindWeakness, FranticMind, Frustration, GatheringEvil, Melt, Overkill, Paralysis, PollutedStrike, Pollute, Strike_Cull, Summoning, WastingStrike, Withering

- Card changes(according to "Cull card changes 20200402"): Abjure, CULLCard, Haunt, Miracle_Cull, Strife, Toil, Wail, WastingForm(WastingEssence)

- Improvements: Catharsis, Counterspell, Firebolt, MistyStep, Mind Glass(relic)

- New keywords: Exert, Exerted, Deck of Trials

- New UI strings: Thirst

### CODE REVIEW

**Comment by dbjorge** [comment]
I've been holding off on approving this because there are still a few suggested text changes in the other CULL PRs that this adds text for; once those are updated, we can get this in (I'd like to do a release at that point so we can start doing balance passes of this batch of CULL cards)

**Comment by yanang007** [comment]
That's understandable. I will continue to work on keeping this up to date.

**Comment by dbjorge** [comment]
I think we're going to try to release in about the state this is currently in! I think the only thing that's missing in this branch is a translation for `stsjorbsmod:EntombedGrimDirgePower`

**Comment by yanang007** [comment]
Ooops, "fatal" missing. I've pushed a new commit to fix it. 
Other improvments will be made according to players' feedback after the official release, so this branch should be stable now.

**Comment by dbjorge** [comment]
FYI: the text on Withering changed a little during the merge of its PR, the name of "WitherPower" changed to "WitheringPower", and its text also changed slightly.

**Comment by dbjorge** [comment]
(That's going to be the last non-translation PR I plan to merge prior to v1.8.0, will release v1.8.0 as soon as the ZHS and SPA translations are updated)

**Comment by yanang007** [comment]
Wow, "Withering" seems much different from what it used to be...

**Pull request merged**
